"""Zero-overlap leakage validation for train/val/test split manifests.

Not runnable yet in a meaningful way: split manifests are generated by
Milestone M3B (not implemented in M3A — see prepare_dataset.py's module
docstring for the milestone boundary). This script is created now so its
shape/contract is fixed, and so `py_compile` can validate its syntax as
part of M3A's validation, but there is nothing for it to check until
ml-service/data/splits/{train,val,test}.csv exist.

Expected CSV schema per split file (produced by Stage 5 / M3B):
    path, class_name, group_key, group_source, sha256

Checks performed once split files exist:
  1. No sha256 value appears in more than one split.
  2. No group_key value appears in more than one split.
Either failure exits non-zero with a report of the offending overlaps.
"""

from __future__ import annotations

import argparse
import csv
import sys
from collections import defaultdict
from pathlib import Path

SPLIT_NAMES = ("train", "val", "test")


def load_split(path: Path):
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows


def check_leakage(splits_dir: Path) -> int:
    missing = [name for name in SPLIT_NAMES if not (splits_dir / f"{name}.csv").exists()]
    if missing:
        print(
            f"No split manifests found for: {', '.join(missing)} under {splits_dir}. "
            "Split generation is scoped to Milestone M3B and has not run yet.",
            file=sys.stderr,
        )
        return 2

    hash_to_splits: dict[str, set[str]] = defaultdict(set)
    group_to_splits: dict[str, set[str]] = defaultdict(set)

    for name in SPLIT_NAMES:
        rows = load_split(splits_dir / f"{name}.csv")
        for row in rows:
            hash_to_splits[row["sha256"]].add(name)
            group_to_splits[row["group_key"]].add(name)

    hash_overlaps = {h: s for h, s in hash_to_splits.items() if len(s) > 1}
    group_overlaps = {g: s for g, s in group_to_splits.items() if len(s) > 1}

    if hash_overlaps or group_overlaps:
        print("LEAKAGE CHECK FAILED", file=sys.stderr)
        if hash_overlaps:
            print(f"  {len(hash_overlaps)} sha256 values appear in multiple splits", file=sys.stderr)
        if group_overlaps:
            print(f"  {len(group_overlaps)} group_key values appear in multiple splits", file=sys.stderr)
        return 1

    print("LEAKAGE CHECK PASSED: zero hash overlap, zero group overlap across train/val/test.")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--splits-dir", required=True, type=Path)
    args = parser.parse_args()
    sys.exit(check_leakage(args.splits_dir))


if __name__ == "__main__":
    main()
