"""Milestone M3B-2A: records AI-ASSISTED PRELIMINARY visual-review
judgments made by inspecting the contact sheets generated by
tomato_filename_group_review.py
(ml-service/data/reports/tomato_filename_review/*.png).

IMPORTANT -- review status: every judgment recorded below is
`review_type: "preliminary_ai_review"`. It was produced by an AI assistant
visually comparing the rendered contact-sheet images, leaf-by-leaf, NOT by
a human reviewer. It is preliminary evidence to inform M3B-2, not final
approval. No group reviewed here is eligible for train/validation/test use.
Final approval of any filename-family grouping rule is a decision that
belongs to the user during Milestone M3B-2, not to this script or its
output. The 6 large chains (size >= 10) additionally require explicit,
individual human review before any sign-off, regardless of their
preliminary AI-assisted judgment here.

Re-running this script does not redo the visual review; it
deterministically re-emits the recorded preliminary judgments and derives
the summary/rule-proposal reports from them.

This script does NOT approve filename-family grouping for split use, does
NOT create approved_phash_groups.json, and does NOT modify split
eligibility anywhere. It only writes the two remaining M3B-2A review
report files, both explicitly labeled as preliminary AI review, not final
human approval.
"""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
import subprocess

ML_SERVICE_ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = ML_SERVICE_ROOT / "data" / "reports"

# ---------------------------------------------------------------------------
# Recorded PRELIMINARY AI REVIEW judgments (review_type:
# "preliminary_ai_review", stamped onto every record at output time by
# _with_review_type() below) from an AI assistant inspecting the 5 contact
# sheet PNGs: tomato_healthy_contact_sheet_{01,02}.png and
# tomato_late_blight_contact_sheet_{01,02,03}.png. NOT final human
# approval; no group here is eligible for train/validation/test use.
#
# Categories (per required schema): same_physical_leaf_likely,
# same_capture_series_likely, visually_related_but_uncertain,
# clearly_different, unreadable_or_invalid. These describe the preliminary
# AI judgment only -- they are deliberately NOT named approved,
# human_approved, eligible_for_split, or final_decision.
# ---------------------------------------------------------------------------

TOMATO_HEALTHY_REVIEW = {
    # All 20 sampled groups: consistent leaf silhouette, vein pattern, and
    # uniform gray background across every member of every group. No Day
    # numbers involved (Tomato Healthy has no Day-suffix convention) -- these
    # read as multiple photographs (different crop/zoom/angle) of one leaf
    # specimen per group, not a time series.
    "th::Leaf166": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Matching lobe pattern and vein structure across both images."},
    "th::Leaf168": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Distinctive large-leaf silhouette matches in both images."},
    "th::Leaf175": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Consistent shape/vein pattern."},
    "th::Leaf176": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Consistent shape/vein pattern."},
    "th::Leaf177": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Consistent shape/vein pattern."},
    "th::Leaf178": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Consistent shape/vein pattern."},
    "th::Leaf179": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Consistent shape/vein pattern."},
    "th::Leaf180": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Consistent shape/vein pattern."},
    "th::Leaf181": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Consistent shape/vein pattern."},
    "th::Leaf182": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Consistent shape/vein pattern."},
    "th::Leaf184": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "All 3 images match silhouette/vein pattern."},
    "th::Leaf188": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "All 3 images match silhouette/vein pattern."},
    "th::Leaf206": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "All 3 images match silhouette/vein pattern."},
    "th::Leaf210": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "All 3 images match silhouette/vein pattern."},
    "th::Leaf213": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "All 3 images match silhouette/vein pattern."},
    "th::Leaf220": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "All 3 images match silhouette/vein pattern."},
    "th::Leaf225": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "All 3 images match silhouette/vein pattern."},
    "th::Leaf236": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "All 3 images match silhouette/vein pattern."},
    "th::Leaf254": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "All 3 images match silhouette/vein pattern."},
    "th::Leaf495": {"size": 4, "judgment": "same_physical_leaf_likely", "note": "Largest sampled Healthy group (4); all 4 still show consistent silhouette/vein pattern, no outliers observed."},
}

TOMATO_LATE_BLIGHT_REVIEW = {
    # GHLB2 family (non-Day, sizes 2-5): consistent lesion shape/location
    # and leaf silhouette across every member of every sampled group.
    "tlb::GHLB2::Leaf100": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Matching lesion pattern."},
    "tlb::GHLB2::Leaf101": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "Matching curled/wilted shape and lesion pattern."},
    "tlb::GHLB2::Leaf102": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Matching shape/lesion."},
    "tlb::GHLB2::Leaf105": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Matching shape/lesion."},
    "tlb::GHLB2::Leaf106": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Matching shape/lesion."},
    "tlb::GHLB2::Leaf107": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "Matching wilted shape across all 3."},
    "tlb::GHLB2::Leaf108": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Matching shape/lesion."},
    "tlb::GHLB2::Leaf109": {"size": 2, "judgment": "same_physical_leaf_likely", "note": "Matching shape/lesion."},
    "tlb::GHLB2::Leaf111": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "Matching shape across all 3."},
    "tlb::GHLB2::Leaf112": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "Matching shape across all 3."},
    "tlb::GHLB2::Leaf113": {"size": 4, "judgment": "same_physical_leaf_likely", "note": "Matching shape across all 4."},
    "tlb::GHLB2::Leaf114": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "Matching shape across all 3."},
    "tlb::GHLB2::Leaf117": {"size": 4, "judgment": "same_physical_leaf_likely", "note": "Matching shape across all 4."},
    "tlb::GHLB2::Leaf121": {"size": 5, "judgment": "same_physical_leaf_likely", "note": "Matching shape across all 5, no outliers observed."},
    "tlb::GHLB2::Leaf145": {"size": 4, "judgment": "same_physical_leaf_likely", "note": "Matching shape across all 4."},
    "tlb::GHLB2::Leaf148": {"size": 4, "judgment": "same_physical_leaf_likely", "note": "Matching shape across all 4."},
    "tlb::GHLB2::Leaf154": {"size": 5, "judgment": "same_physical_leaf_likely", "note": "Matching shape across all 5, no outliers observed."},
    "tlb::GHLB2ES::Leaf119": {"size": 3, "judgment": "same_physical_leaf_likely", "note": "Matching shape across all 3; only GHLB2ES multi-image group with distinct representation in sample."},

    # GHLB family (Day-suffixed, gray background): visually consistent
    # leaf silhouette across each day-progression sequence -- read as a
    # disease-progression time series of one leaf, not independent leaves.
    "tlb::GHLB::Leaf1": {"size": 10, "judgment": "same_capture_series_likely", "note": "Day-based progression, consistent silhouette across sequence. LARGE CHAIN (10) -- flagged for extra caution, see limitations."},
    "tlb::GHLB::Leaf2": {"size": 17, "judgment": "same_capture_series_likely", "note": "Day-based progression, consistent silhouette across sequence. LARGE CHAIN (17, largest in entire sample) -- flagged for extra caution, see limitations."},
    "tlb::GHLB::Leaf23": {"size": 14, "judgment": "same_capture_series_likely", "note": "Day-based progression (green to necrotic/curled), consistent silhouette. LARGE CHAIN (14) -- flagged for extra caution."},
    "tlb::GHLB::Leaf8": {"size": 7, "judgment": "same_capture_series_likely", "note": "Day-based progression, consistent silhouette across 7 images."},

    # GHLB_PS family (Day-suffixed, black background): the clearest
    # evidence in the whole sample -- distinctive leaf silhouette/vein
    # pattern remains recognizable through a visible green-to-necrotic
    # progression consistent with disease-progression time-lapse
    # photography of a single suspended leaf.
    "tlb::GHLB_PS::Leaf1": {"size": 15, "judgment": "same_capture_series_likely", "note": "Very clear same-leaf time series (black background, consistent silhouette through progression). LARGE CHAIN (15) -- flagged for extra caution."},
    "tlb::GHLB_PS::Leaf2": {"size": 13, "judgment": "same_capture_series_likely", "note": "Very clear same-leaf time series. LARGE CHAIN (13) -- flagged for extra caution."},
    "tlb::GHLB_PS::Leaf23": {"size": 9, "judgment": "same_capture_series_likely", "note": "Clear same-leaf time series, consistent silhouette."},
    "tlb::GHLB_PS::Leaf24": {"size": 9, "judgment": "same_capture_series_likely", "note": "Clear same-leaf time series, consistent silhouette."},
    "tlb::GHLB_PS::Leaf25": {"size": 5, "judgment": "same_capture_series_likely", "note": "Clear same-leaf time series, consistent silhouette."},
    "tlb::GHLB_PS::Leaf26": {"size": 9, "judgment": "same_capture_series_likely", "note": "Clear same-leaf time series, consistent silhouette."},
    "tlb::GHLB_PS::Leaf28": {"size": 6, "judgment": "same_capture_series_likely", "note": "Clear same-leaf time series, consistent silhouette."},
    "tlb::GHLB_PS::Leaf8": {"size": 10, "judgment": "same_capture_series_likely", "note": "Clear same-leaf time series. LARGE CHAIN (10) -- flagged for extra caution."},
}

LARGE_CHAIN_THRESHOLD = 10  # groups at/above this size are flagged for extra scrutiny, not blind trust


def _write_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2, sort_keys=True)


def _agriai_repo_commit():
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=ML_SERVICE_ROOT.parent,
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip()
    except Exception:
        return None


def _with_review_type(records: dict) -> dict:
    """Returns a copy of the group records with review_type explicitly
    stamped on every entry -- preliminary_ai_review, never approved/
    human_approved/eligible_for_split/final_decision."""
    out = {}
    for k, v in records.items():
        out[k] = {**v, "review_type": "preliminary_ai_review"}
    return out


def build_review_summary():
    all_judgments = {**TOMATO_HEALTHY_REVIEW, **TOMATO_LATE_BLIGHT_REVIEW}
    counts = Counter(v["judgment"] for v in all_judgments.values())

    large_chains = [
        {
            "group_key": k,
            "size": v["size"],
            "requires_explicit_individual_human_review": True,
            "note": "Preliminary AI review supports this being one leaf end-to-end, but size >= 10 requires the user to individually review this specific group during M3B-2 before any sign-off -- not covered by a blanket approval of the rule.",
        }
        for k, v in TOMATO_LATE_BLIGHT_REVIEW.items()
        if v["size"] >= LARGE_CHAIN_THRESHOLD
    ]

    summary = {
        "review_type": "preliminary_ai_review",
        "review_status_statement": (
            "AI-ASSISTED PRELIMINARY REVIEW, NOT FINAL HUMAN APPROVAL. All "
            "50 sampled groups below received preliminary_ai_review only -- "
            "an AI assistant visually compared the rendered contact-sheet "
            "images. No filename-family group, of any judgment value, is "
            "eligible for train/validation/test use as a result of this "
            "review. Final approval of the proposed rules is a decision "
            "that belongs to the user during Milestone M3B-2. The 6 large "
            "chains (size >= 10) additionally require explicit, individual "
            "human review before any sign-off, regardless of their "
            "preliminary_ai_review judgment."
        ),
        "approval_authority": "user_during_m3b2",
        "split_eligibility_status": "not_eligible -- pending M3B-2 user approval",
        "method": (
            "Every sampled group's contact sheet was visually inspected "
            "(all member thumbnails compared leaf-by-leaf for silhouette, "
            "vein pattern, lesion location/shape, and background "
            "consistency) before recording a preliminary_ai_review judgment. "
            "Filenames sharing a number were never treated as approved "
            "merely because they share a number -- judgment was based on "
            "the rendered images. This method describes an AI-assisted "
            "preliminary pass, not a human review process."
        ),
        "sampled_group_count": len(all_judgments),
        "tomato_healthy_sampled_group_count": len(TOMATO_HEALTHY_REVIEW),
        "tomato_late_blight_sampled_group_count": len(TOMATO_LATE_BLIGHT_REVIEW),
        "judgment_counts": dict(counts),
        "same_physical_leaf_likely_count": counts.get("same_physical_leaf_likely", 0),
        "same_capture_series_likely_count": counts.get("same_capture_series_likely", 0),
        "visually_related_but_uncertain_count": counts.get("visually_related_but_uncertain", 0),
        "clearly_different_count": counts.get("clearly_different", 0),
        "unreadable_or_invalid_count": counts.get("unreadable_or_invalid", 0),
        "large_chain_threshold": LARGE_CHAIN_THRESHOLD,
        "large_chains_flagged_for_extra_caution": large_chains,
        "per_group": {
            "tomato_healthy": _with_review_type(TOMATO_HEALTHY_REVIEW),
            "tomato_late_blight": _with_review_type(TOMATO_LATE_BLIGHT_REVIEW),
        },
        "overall_finding": (
            "Under preliminary_ai_review, no sampled group (50 of 50) was "
            "judged clearly_different or unreadable_or_invalid. All Tomato "
            "Healthy groups (20/20) received a preliminary_ai_review "
            "judgment of same_physical_leaf_likely. All Tomato Late Blight "
            "groups (30/30) received a preliminary_ai_review judgment of "
            "same_physical_leaf_likely (non-Day families) or "
            "same_capture_series_likely (Day-suffixed families, consistent "
            "with disease-progression time-lapse photography). 6 of the 30 "
            "Late Blight groups are large chains (size >= 10, up to 17) and "
            "are explicitly flagged as requiring individual human review: "
            "preliminary AI review at thumbnail resolution supports these "
            "being one leaf end-to-end, but per the M3B plan's "
            "anti-chaining caution, large chains must not be trusted on the "
            "strength of this preliminary pass alone -- explicit, "
            "individual user review during M3B-2 is required before any "
            "sign-off, in addition to safeguards such as a maximum group "
            "size cap or splitting into day-adjacent sub-chains. THIS "
            "PRELIMINARY REVIEW DOES NOT MAKE ANY GROUP ELIGIBLE FOR "
            "TRAIN/VALIDATION/TEST USE."
        ),
    }
    return summary


def build_rule_proposal():
    proposal = {
        "status": "proposed_not_approved",
        "review_type": "preliminary_ai_review",
        "approval_authority": "user_during_m3b2",
        "split_eligibility_status": "not_eligible -- pending M3B-2 user approval",
        "review_status_statement": (
            "The evidence in this proposal (including the visual-review "
            "findings it cites) was produced by AI-assisted preliminary "
            "review, not final human approval. Nothing in this file makes "
            "any group eligible for train/validation/test use. Approving "
            "or rejecting these proposed rules is a decision for the user "
            "during Milestone M3B-2."
        ),
        "tomato_healthy": {
            "regex": r"^GH_HL Leaf (\d+)(\.(\d+))?\s*$",
            "normalization": "Strip a leading <uuid>___ prefix (regex [0-9a-f]{8}-...-[0-9a-f]{12}___) if present, strip the final .jpg/.jpeg extension, then match the pattern above case-insensitively.",
            "grouping_key": "th::Leaf<N> (decimal sub-index N.sub is stripped and NOT part of the key)",
            "fields_preserved": ["leaf_number"],
            "fields_removed": ["sub_index (folded into the same group)", "uuid_prefix"],
            "known_limitations": [
                "3 of 592 filenames do not match this pattern at all (0.51%): 1 double-extension typo ('...380.1JPG.JPG'), 1 unrelated 'CG1.JPG' naming convention, 1 Flickr-style numeric ID -- these remain unresolved/quarantined under this rule, not force-fitted.",
                "No authoritative CSV precedent exists for the decimal-suffix convention (0 decimal-suffixed rows found in any of the 3 fetched Tomato CSVs) -- the rule rests entirely on visual review, not upstream corroboration.",
                "Visual review was at thumbnail resolution (140x140px); not a substitute for full-resolution or botanical expert review.",
            ],
            "evidence_supporting_the_rule": "20/20 sampled multi-image groups (sizes 2-4) received a preliminary_ai_review judgment of same_physical_leaf_likely -- consistent leaf silhouette, vein pattern, and uniform background across every member of every sampled group. No clearly_different or uncertain cases found in the sample.",
            "estimated_images_recoverable_if_approved": {
                "groups": 360,
                "images_in_multi_member_groups": 592 - 157 - 3,  # total - singleton-only-images - malformed
                "images_including_singletons": 592 - 3,
                "note": "This is an ESTIMATE of images that would gain a group_source if the rule is approved in M3B-2 -- singleton groups (157) still count as 'grouped' in the sense of having a defined key, but contribute no leakage-prevention benefit beyond what a correctly-scoped singleton already provides.",
            },
        },
        "tomato_late_blight": {
            "regex": r"^(GHLB2ES|GHLB2|GHLB_PS|GHLB)\s+Leaf\s+(\d+)(\.(\d+))?(\s+Day\s*(\d+))?\s*$",
            "normalization": "Strip a leading <uuid>___ prefix if present, strip the final .jpg/.jpeg extension, then match the pattern above case-insensitively. Session prefix is matched longest-first (GHLB2ES/GHLB2/GHLB_PS before GHLB) to avoid a shorter prefix accidentally matching a longer one.",
            "grouping_key": "tlb::<session_prefix>::Leaf<N> (decimal sub-index AND Day number are both stripped and NOT part of the key -- both fold into the same group as the base leaf+prefix)",
            "fields_preserved": ["session_prefix", "leaf_number"],
            "fields_removed": ["sub_index", "day_number", "uuid_prefix"],
            "known_limitations": [
                "0 of 989 filenames failed to match (100% parse rate) -- but this does not mean 100% should be grouped as one leaf per prefix+number; see large-chain caution below.",
                "Session prefix MUST be part of the key -- X leaf numbers are reused across different session prefixes (see collision report); grouping by leaf number alone would incorrectly merge unrelated leaves from different experimental batches.",
                "6 of the resulting multi-image groups are 'large chains' (size 10-17) built by collapsing both decimal-suffix AND Day-number variation into one group. Visual review supports these being genuine same-leaf time series, but a 10-17-image chain is exactly the scenario the M3B plan's anti-transitive-chaining caution was written for -- recommend NOT approving these at full size without an additional safeguard (e.g. a documented maximum group size, or explicit sub-review of the largest chains specifically) before M3B-2 sign-off.",
                "No authoritative CSV precedent exists for either the decimal-suffix or Day-suffix convention (0 such rows found in the fetched Tomato Late Blight CSV).",
            ],
            "evidence_supporting_the_rule": "30/30 sampled groups (17 non-Day GHLB2/GHLB2ES groups, sizes 2-5, and 12 Day-suffixed GHLB/GHLB_PS groups, sizes 5-17) received a preliminary_ai_review judgment of same_physical_leaf_likely or same_capture_series_likely. The GHLB_PS (black background) sequences in particular show a clear, consistent leaf silhouette through a visible green-to-necrotic disease progression -- the strongest evidence in the entire review. No clearly_different cases found.",
            "estimated_images_recoverable_if_approved": {
                "groups": 712,
                "images_in_multi_member_groups": 989 - 585,
                "images_including_singletons": 989,
                "note": "Same caveat as Tomato Healthy regarding singleton groups. If the 6 large chains (>=10) are excluded pending further review, the multi-member-group image count drops accordingly -- exact figure requires the M3B-2 decision on the large-chain caution.",
            },
        },
        "tomato_early_blight": {
            "regex": None,
            "normalization": None,
            "grouping_key": None,
            "fields_preserved": [],
            "fields_removed": [],
            "known_limitations": ["Only 1 unmatched image exists -- a single image cannot demonstrate a filename family or be visually compared against anything."],
            "evidence_supporting_the_rule": "None -- no rule proposed.",
            "estimated_images_recoverable_if_approved": {"groups": 0, "images_in_multi_member_groups": 0, "images_including_singletons": 0},
            "recommendation": "Keep quarantined unless direct evidence (e.g. a future authoritative match) supports inclusion.",
        },
        "overall_recommendation": (
            "Both Tomato Healthy and Tomato Late Blight candidate rules are "
            "supported by consistent visual evidence in this sample and are "
            "reasonable to bring to M3B-2 for formal approval. The Late "
            "Blight rule's 6 large chains (size >= 10) should be "
            "specifically called out for a separate, explicit sign-off "
            "decision (approve at full size vs. cap/split) rather than "
            "bundled into a single blanket approval. This proposal does "
            "NOT constitute that approval -- M3B-2A intentionally stops "
            "here."
        ),
    }
    return proposal


def run():
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    summary = build_review_summary()
    _write_json(REPORTS_DIR / "tomato_filename_group_review_summary.json", summary)

    proposal = build_rule_proposal()
    _write_json(REPORTS_DIR / "tomato_filename_rule_proposal.json", proposal)

    return summary, proposal


if __name__ == "__main__":
    summary, proposal = run()
    print(json.dumps({k: v for k, v in summary.items() if k != "per_group"}, indent=2))
